### ISSUE TITLE
[Feature] - Add circles

### ISSUE THREAD

**Issue by breck7** [astashov/tixi#32]
Or else idiots draw things like this:

https://www.reddit.com/r/dataisugly/comments/mfx6td/ascii_venn_diagram/

**Comment by astashov** [comment]
Lol, this is hilarious! :)

Unfortunately, I don't have bandwidth to maintain Textik anymore, I keep it working, but didn't add any new features in a while. Sorry...

**Comment by breck7** [comment]
Np! It is open source (thank you!) so if I truly needed it you've given me the power to build it myself.
