### ISSUE TITLE
"Show Result" doesn't work for me

### ISSUE THREAD

**Issue by iohn2000** [astashov/tixi#6]
I'm drawing a diagram and click the "Show Result" Icon.
At best I get the last objet I created but not the whole diagram.

I'm using windows and chrome 43.0
![textik](https://cloud.githubusercontent.com/assets/12810916/8053991/81bec9de-0e95-11e5-9770-75a629a656da.PNG)

**Comment by astashov** [comment]
I'm sorry, but I'm frankly don't support this project anymore, it was just a pet project to try out ClojureScript. I probably will take a look at the bug, but that won't happen soon.

**Comment by iohn2000** [comment]
No worries, just thought I report it...
Happens all the time People move on to newer and more exciting pets :-)

**Comment by astashov** [comment]
Yeah, and thanks for the report!

**Comment by obnoxxx** [comment]
same here. firefox and chromium. it's a pity you don't maintain it any more. great tool!

**Comment by astashov** [comment]
I'm about to relaunch it and then continue developing. Stay tuned. :)

**Comment by obnoxxx** [comment]
@astashov cool, i'll be watching... :-)

**Comment by ChrLipp** [comment]
The export works when there are only some elements (with 3 it worked). But once it has more elements (in my case 12) only the last element is exported.

**Comment by obnoxxx** [comment]
@ChrLipp that matches my experience.

**Comment by slowfranklin** [comment]
This thing is just so awesome, it would be really, really great to see this issue fixed. If there was a donate button, I wouldn't hesitate and sponsor this.

**Comment by astashov** [comment]
That's amazing to hear :) I think I'll fix it by the end of the year.

**Comment by astashov** [comment]
Could somebody check if that still happens? Thanks!

**Comment by slowfranklin** [comment]
Seems to work much better now, thanks! And Happy Christmas!

**Comment by astashov** [comment]
Cool!
