### ISSUE TITLE
Browser freezes while generating text version

### ISSUE THREAD

**Issue by ziolek** [astashov/tixi#9]
Whenever I use lines with text browser freezes.

**Comment by astashov** [comment]
What browser? What OS? Could you provide an example?

**Comment by ziolek** [comment]
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36`

This works:
https://textik.com/#37a8c070a04d1ff3

This doesn't:
https://textik.com/#2292abefabc5c4cf

**Comment by astashov** [comment]
Ah, whoops. Thanks for reporting. Will try to fix soon.

**Comment by astashov** [comment]
Thanks for reporting! Should be fixed now.
